# Generated by Django 5.0.3 on 2024-03-07 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wzxblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reguser',
            old_name='head_ing',
            new_name='head_img',
        ),
    ]
