# Generated by Django 5.0.3 on 2024-03-07 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wzxblog', '0003_category_tag_bloginfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloginfo',
            options={'ordering': ['-create_time'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
    ]
